<#
.SYNOPSIS
    Turn staged screenshots into addon-ready cutouts, and write the manifest.

.DESCRIPTION
    An addon cannot write image files, so the matte has to happen outside the
    game. This is that step, reduced to one command: it runs the converter,
    files the TGA under the addon's Media\Cutouts, and regenerates the Lua
    manifest the Roster scene reads.

    With -Watch it sits on the Screenshots folder and does all of that the
    moment a new pair appears, so the in-game flow is just:

        log in on an alt  ->  /asrender  ->  done

    The heavy per-pixel work stays in Python (Pillow): the same loop written in
    PowerShell takes minutes per image rather than seconds.

.PARAMETER Watch
    Keep running and convert each new pair as it is captured. Ctrl-C to stop.

.PARAMETER Shots
    The client's Screenshots folder. Defaults to the standard beta install.

.PARAMETER AddOnsPath
    Where to file the finished TGA. Defaults to the standard beta install.

.EXAMPLE
    pwsh Tools/RenderCutout/Update-Cutouts.ps1
    pwsh Tools/RenderCutout/Update-Cutouts.ps1 -Watch
#>
[CmdletBinding()]
param(
    [switch] $Watch,
    [string] $Shots = "C:\Program Files (x86)\World of Warcraft\_classic_beta_\Screenshots",
    [string] $AddOnsPath = "C:\Program Files (x86)\World of Warcraft\_classic_beta_\Interface\AddOns"
)

$ErrorActionPreference = 'Stop'
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$converter = Join-Path $here 'make-cutout.py'
$outDir = Join-Path $here 'out'
$mediaDir = Join-Path $AddOnsPath 'AltStable\Media\Cutouts'
$manifest = Join-Path $AddOnsPath 'AltStable\CutoutManifest.lua'

function Test-Prereqs {
    $python = Get-Command python -ErrorAction SilentlyContinue
    if (-not $python) { throw "python is not on PATH - the matte needs it (with Pillow)" }
    & python -c "import PIL" 2>$null
    if ($LASTEXITCODE -ne 0) { throw "Pillow is missing:  python -m pip install pillow" }
    if (-not (Test-Path $converter)) { throw "converter not found at $converter" }
}

# One pair -> one TGA, filed where the addon can load it.
function Convert-Newest {
    $before = @(Get-ChildItem $outDir -Filter *.tga -ErrorAction SilentlyContinue |
                Select-Object -ExpandProperty Name)

    & python $converter --shots $Shots
    if ($LASTEXITCODE -ne 0) { Write-Warning "converter failed"; return }

    New-Item -ItemType Directory -Force -Path $mediaDir | Out-Null
    $made = Get-ChildItem $outDir -Filter *.tga | Sort-Object LastWriteTime -Descending |
            Select-Object -First 1
    if (-not $made) { Write-Warning "no TGA produced"; return }

    Copy-Item $made.FullName (Join-Path $mediaDir $made.Name) -Force
    Write-Host ("  filed -> {0}" -f (Join-Path $mediaDir $made.Name)) -ForegroundColor Green

    if ($before -notcontains $made.Name) { Write-Host "  (new character)" -ForegroundColor DarkGray }
    Write-Manifest
}

# The manifest is regenerated wholesale from what is on disk, so deleting a TGA
# is all it takes to retire a character - no second place to edit.
function Write-Manifest {
    $entries = foreach ($tga in (Get-ChildItem $mediaDir -Filter *.tga -ErrorAction SilentlyContinue | Sort-Object Name)) {
        $slug = [IO.Path]::GetFileNameWithoutExtension($tga.Name)
        $dims = & python -c @"
import sys
from PIL import Image
im = Image.open(r'$($tga.FullName)')
bbox = im.convert('RGBA').getbbox()
print(bbox[2]-bbox[0], bbox[3]-bbox[1], im.size[0], im.size[1])
"@
        $w, $h, $tw, $th = $dims -split '\s+'
        "    ['$slug'] = { file = [[Interface\AddOns\AltStable\Media\Cutouts\$($tga.Name)]], w = $w, h = $h, texw = $tw, texh = $th },"
    }

    $lua = @"
-- CutoutManifest.lua - GENERATED by Tools/RenderCutout/Update-Cutouts.ps1
--
-- One entry per character cutout on disk. w/h are the CONTENT size; texw/texh
-- are the power-of-two canvas the image sits in the top-left of, so the UI can
-- crop back to the figure. Regenerated wholesale: delete a TGA to retire a
-- character, do not hand-edit this file.
--
-- Generated $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

AltStableCutoutManifest = {
$($entries -join "`n")
}
"@
    Set-Content -Path $manifest -Value $lua -Encoding UTF8
    Write-Host ("  manifest -> {0}" -f $manifest) -ForegroundColor Green
}

Test-Prereqs

if (-not $Watch) {
    Convert-Newest
    return
}

Write-Host "Watching $Shots - capture with /asrender in game. Ctrl-C to stop." -ForegroundColor Cyan
$seen = @{}
Get-ChildItem $Shots -Filter *.tga -ErrorAction SilentlyContinue | ForEach-Object { $seen[$_.Name] = $true }

while ($true) {
    Start-Sleep -Seconds 2
    $fresh = @(Get-ChildItem $Shots -Filter *.tga -ErrorAction SilentlyContinue |
               Where-Object { -not $seen.ContainsKey($_.Name) } |
               Sort-Object LastWriteTime)
    if ($fresh.Count -ge 2) {
        # A capture is a PAIR. Wait for both before converting, or the matte
        # reads one shot against an older, unrelated one.
        $fresh | ForEach-Object { $seen[$_.Name] = $true }
        Write-Host ("pair: {0}, {1}" -f $fresh[-2].Name, $fresh[-1].Name)
        Convert-Newest
    }
}
